name: Horizons
description: Horizons template for Jekyll

author:
  name      : 'Quantum development group'
  #email    : hi@nandomoreira.me
  url       : "https://quantchemdev.github.io" # the base hostname & protocol for your site
  baseurl   : '/' #subpath of the web
  #facebook : http://facebook.com/fernando.dev
  #twitter  : http://twitter.com/nandomoreirame

github: https://github.com/quantchemdev
#disqus_shortname: "fernandomoreira"
#google_analytics: UA-52446115-1
sass:
  sass_dir: assets/css
 
plugins: [jekyll-paginate]
paginate: 4
paginate_path: "/blog/page:num/"

collections:
  members:
    output: true
    permalink: /members/:path/
  publications:
    output: true
    permalink: /publications/:path/

#paginate: 10  # Número de publicaciones por página
#paginate_path: "/publications/page:num"

plugins:
  - jekyll-scholar

scholar:
  style: apa # Puedes cambiar el estilo de citas, por ejemplo, APA o IEEE
  source: _bibliography
  bibliography: references.bib # Archivo BibTeX con tus referencias
